### ISSUE TITLE
Volume rendering is broken

### ISSUE THREAD

**Issue by banesullivan** [Kitware/trame-vtk#44]
I can't get volume rendering to work with any client-side views right now

```py
"""Validate volume rendering with VTK.js."""

import pyvista as pv
import numpy as np
from trame.app import get_server
from trame.ui.vuetify import SinglePageLayout
from trame.widgets import vuetify, html
from trame.widgets.vtk import VtkLocalView, VtkRemoteView

# Just for using this script in testing
from trame_client.utils.testing import enable_testing

server = enable_testing(get_server(), "local_rendering_ready")
state, ctrl = server.state, server.controller

state.trame__title = "Volume Validation"
state.local_rendering_ready = 0

# -----------------------------------------------------------------------------

image = pv.Wavelet()

plotter = pv.Plotter(off_screen=True)
actor = plotter.add_volume(image)
plotter.reset_camera()


# -----------------------------------------------------------------------------
# GUI
# -----------------------------------------------------------------------------

with SinglePageLayout(server) as layout:
    layout.icon.click = ctrl.view_reset_camera
    layout.title.set_text(state.trame__title)

    with layout.toolbar:
        vuetify.VSpacer()
        html.Div("{{ local_rendering_ready }}", classes="readyCount")

    with layout.content:
        with vuetify.VContainer(
            fluid=True,
            classes="pa-0 fill-height",
        ):
            with vuetify.VCol(classes="fill-height"):
                view = VtkLocalView(
                    plotter.ren_win,
                    on_ready="local_rendering_ready++",
                )
                ctrl.view_update = view.update
                ctrl.view_reset_camera = view.reset_camera
            with vuetify.VCol(classes="fill-height"):
                VtkRemoteView(plotter.ren_win)

    # hide footer
    layout.footer.hide()

# -----------------------------------------------------------------------------
# Main
# -----------------------------------------------------------------------------

if __name__ == "__main__":
    server.start()
```

**Comment by banesullivan** [comment]
Seeing this in JS console:

```
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'set')
    at Object.r [as registerInstance] (trame-vtk.js:3450:72118)
    at trame-vtk.js:3450:64758
    at Array.forEach (<anonymous>)
    at Object.ut [as update] (trame-vtk.js:3450:64568)
    at ts (trame-vtk.js:3450:63650)
    at trame-vtk.js:3450:64781
    at Array.forEach (<anonymous>)
    at ut (trame-vtk.js:3450:64568)
    at Object.oM [as update] (trame-vtk.js:3450:65403)
    at ts (trame-vtk.js:3450:63650)
```

**Comment by banesullivan** [comment]
This was a browser caching issue. All seems to be working now

**Comment by jourdain** [comment]
`No builder for vtkSmartVolumeMapper`

**Comment by jourdain** [comment]
Fixed the error by adding an alias but the rendering is still empty...

**Comment by jourdain** [comment]
Any reason for 2 fields with a weird one set at setScalars?
```
{
					"parent": "000000013df054a0",
					"id": "000000013df054a0-dataset",
					"type": "vtkImageData",
					"properties": {
						"spacing": [1.0, 1.0, 1.0],
						"origin": [0.0, 0.0, 0.0],
						"extent": [-10, 10, -10, 10, -10, 10],
						"direction": [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0],
						"fields": [{
							"hash": "d42f855c14d32707570a50f67ab96952_9261f",
							"vtkClass": "vtkDataArray",
							"name": "RTData",
							"dataType": "Float32Array",
							"numberOfComponents": 1,
							"size": 9261,
							"ranges": [{
								"min": 37.35310363769531,
								"max": 276.8288269042969,
								"component": null
							}],
							"location": "pointData",
							"registration": "addArray"
						}, {
							"hash": "8f1bb27011e27e1f5d3ea5798bd2b93a_9261f",
							"vtkClass": "vtkDataArray",
							"name": "Data",
							"dataType": "Float32Array",
							"numberOfComponents": 1,
							"size": 9261,
							"ranges": [{
								"min": 0.0,
								"max": 255.0,
								"component": null
							}],
							"location": "pointData",
							"registration": "setScalars"
						}]
					}
				}
```

**Comment by jourdain** [comment]
Seems to be a blend of PyVista and trame-vtk expectation. 

As I remember, the vtkSmartVolumeMapper prevent us to grab proper info from the concrete mapper. At some point you did something to override the vtkSmartVolumeMapper by a concrete one within PyVista...

**Comment by jourdain** [comment]
The VTK volume rendering example is working.

**Comment by banesullivan** [comment]
Which example? Is it using `vtkFixedPointVolumeRayCastMapper` because that is the only volume mapper class I can get to work with the current serializer. `vtkOpenGLGPUVolumeRayCastMapper`, `vtkGPUVolumeRayCastMapper`, and `vtkSmartVolumeMapper` are all failing

**Comment by jourdain** [comment]
Yes just tested `vtkFixedPointVolumeRayCastMapper`
